name: Test PowerShell
on: push

jobs:
  pester-test:
    name: Pester test
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Perform a Pester test from the command-line
        run: installgoogle | Should -Be $true

